name: Sync Fork

on:
  schedule:
    - cron: '0 4 * * 1' # Every Monday morning
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: alxshelepenok
